# Site settings
title: Zheng Yuan
description: Zheng Yuan's Blog
baseurl: ""
url: zhengyuen.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zheng Yuan
user_description: Currently studying M.Sc. Cognitive and Computational Neuroscience.
user_title: Graduate Student @ University of Sheffield
my_email: zhengyuen.aries@gmail.com
my_instagram : https://www.instagram.com/zhengyuan.aries/
my_twitter: https://twitter.com/zhengyuen94/
my_facebook: https://www.facebook.com/zhengyuan.49/
my_github:  https://github.com/ZhengYuen/
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
