# Site settings
title: Zheng's Website
description: This is Zheng Yuan's personal website.
baseurl: ""
url: zhengyuen.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zheng Yuan
user_description: Currently studying M.Sc. Cognitive and Computational Neuroscience.
user_title: #
my_school: University of Sheffield
my_email: zhengyuen.aries@gmail.com
my_instagram : https://www.instagram.com/zhengyuan.aries/
my_twitter: https://twitter.com/zhengyuen94/
my_facebook: https://www.facebook.com/zhengyuan.49/
my_github:  https://github.com/ZhengYuen/
my_linkedin: https://www.linkedin.com/in/zhengyuen/
my_motto: Elegance is an attitude.
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-cayman